import React from 'react';
import { AbsoluteFill, Audio, Sequence, staticFile } from 'remotion';
import { ZegamaIntro } from '../scenes/ZegamaIntro';
import { FlybyScene } from '../scenes/FlybyScene';
import { ZegamaOutro } from '../scenes/ZegamaOutro';
import { INTRO_DURATION, FLYBY_DURATION, OUTRO_DURATION, TOTAL_FRAMES } from '../utils/routeTimeline';

export { TOTAL_FRAMES };

export const ZegamaVideo: React.FC = () => {
  const flybyStart = INTRO_DURATION;
  const outroStart = INTRO_DURATION + FLYBY_DURATION;

  return (
    <AbsoluteFill style={{ background: '#0A0A0F' }}>
      {/* Google Fonts */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Anton&family=Inter:wght@300;400;600;700&family=JetBrains+Mono:wght@400;700&display=swap');
      `}</style>

      {/* ── Audio (generated by scripts/generate-audio.mjs) ──────────────
          Run: node scripts/generate-audio.mjs
          Then: the file public/epic-zegama.wav will be used here.
          If missing, the video renders silently.
      ───────────────────────────────────────────────────────────────────── */}
      <Audio src={staticFile('epic-zegama.wav')} />

      {/* ── Intro ──────────────────────────────────────────────────────── */}
      <Sequence from={0} durationInFrames={INTRO_DURATION}>
        <ZegamaIntro />
      </Sequence>

      {/* ── Flyby ──────────────────────────────────────────────────────── */}
      <Sequence from={flybyStart} durationInFrames={FLYBY_DURATION}>
        <FlybyScene />
      </Sequence>

      {/* ── Outro ──────────────────────────────────────────────────────── */}
      <Sequence from={outroStart} durationInFrames={OUTRO_DURATION}>
        <ZegamaOutro />
      </Sequence>
    </AbsoluteFill>
  );
};
